apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jojohomelab-admins-role-binding
subjects:
- kind: User
  name: jojo-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: jojohomelab-admins
  apiGroup: rbac.authorization.k8s.io
