apiVersion: v1
kind: Pod
metadata:
  name: service-account-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
  serviceAccountName: dashboard-sa
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In ## NotIn and Exists are other options
            values:
            - Large
            - Medium
