apiVersion: v1
kind: LimitRange
metadata:
  name: memory-resource-constraint
spec:
  limits:
  - default:
      memory: 1Gi       # Limit
    defaultRequest:
      memory: 1Gi       # Request
    max:
      memory: 1Gi       # Limit
    min:
      memory: 500Mi     # Request
    type: Container
