apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv-vol1
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
