apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - while true; do date >> /data/output.log; sleep 5; done
      volumeMounts:
        - mountPath: /data
          name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: pvc-vol1
